/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CreateRouteImport } from './routes/create'
import { Route as GameRouteImport } from './routes/game'
import { Route as GroupRouteImport } from './routes/group'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SpotRouteImport } from './routes/spot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRoute = GroupRouteImport.update({
  id: '/group',
  path: '/group',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotRoute = SpotRouteImport.update({
  id: '/spot',
  path: '/spot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/create': typeof CreateRoute
  '/game': typeof GameRoute
  '/group': typeof GroupRoute
  '/identify': typeof IdentifyRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/rankings': typeof RankingsRoute
  '/results': typeof ResultsRoute
  '/spot': typeof SpotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/create': typeof CreateRoute
  '/game': typeof GameRoute
  '/group': typeof GroupRoute
  '/identify': typeof IdentifyRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/rankings': typeof RankingsRoute
  '/results': typeof ResultsRoute
  '/spot': typeof SpotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/create': typeof CreateRoute
  '/game': typeof GameRoute
  '/group': typeof GroupRoute
  '/identify': typeof IdentifyRoute
  '/join': typeof JoinRoute
  '/lobby': typeof LobbyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/rankings': typeof RankingsRoute
  '/results': typeof ResultsRoute
  '/spot': typeof SpotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/create'
    | '/game'
    | '/group'
    | '/identify'
    | '/join'
    | '/lobby'
    | '/profile'
    | '/progress'
    | '/rankings'
    | '/results'
    | '/spot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/create'
    | '/game'
    | '/group'
    | '/identify'
    | '/join'
    | '/lobby'
    | '/profile'
    | '/progress'
    | '/rankings'
    | '/results'
    | '/spot'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/create'
    | '/game'
    | '/group'
    | '/identify'
    | '/join'
    | '/lobby'
    | '/profile'
    | '/progress'
    | '/rankings'
    | '/results'
    | '/spot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  CreateRoute: typeof CreateRoute
  GameRoute: typeof GameRoute
  GroupRoute: typeof GroupRoute
  IdentifyRoute: typeof IdentifyRoute
  JoinRoute: typeof JoinRoute
  LobbyRoute: typeof LobbyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RankingsRoute: typeof RankingsRoute
  ResultsRoute: typeof ResultsRoute
  SpotRoute: typeof SpotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group': {
      id: '/group'
      path: '/group'
      fullPath: '/group'
      preLoaderRoute: typeof GroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spot': {
      id: '/spot'
      path: '/spot'
      fullPath: '/spot'
      preLoaderRoute: typeof SpotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  CreateRoute: CreateRoute,
  GameRoute: GameRoute,
  GroupRoute: GroupRoute,
  IdentifyRoute: IdentifyRoute,
  JoinRoute: JoinRoute,
  LobbyRoute: LobbyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RankingsRoute: RankingsRoute,
  ResultsRoute: ResultsRoute,
  SpotRoute: SpotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
